#############################################################################
# Makefile for building: VocabBuilder
# Generated by qmake (3.0) (Qt 5.1.1) on: Sat Oct 29 14:46:35 2016
# Project:  VocabBuilder.pro
# Template: app
# Command: C:/qt51/5.1.1/mingw48_32/bin/qmake.exe -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VocabBuilder.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:/qt51/5.1.1/mingw48_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: VocabBuilder.pro ../../qt51/5.1.1/mingw48_32/mkspecs/win32-g++/qmake.conf ../../qt51/5.1.1/mingw48_32/mkspecs/features/spec_pre.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/qdevice.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/device_config.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/common/shell-unix.conf \
		../../qt51/5.1.1/mingw48_32/mkspecs/qconfig.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axbase.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axserver.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_clucene.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_core.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_declarative.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_designer.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_designercomponents.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_gui.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_help.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_network.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_opengl.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_platformsupport.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qml.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_quick.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_quickparticles.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_script.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_sensors.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_serialport.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_sql.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_svg.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_testlib.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_uitools.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_v8.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_webkit.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_widgets.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_xml.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/qt_functions.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/qt_config.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/win32-g++/qmake.conf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/spec_post.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/exclusive_builds.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/default_pre.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/default_pre.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/resolve_config.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/default_post.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/qml_debug.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/declarative_debug.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/rtti.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/warn_on.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/qt.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/resources.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/moc.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/opengl.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/uic.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/windows.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/testcase_targets.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/exceptions.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/yacc.prf \
		../../qt51/5.1.1/mingw48_32/mkspecs/features/lex.prf \
		VocabBuilder.pro \
		C:/qt51/5.1.1/mingw48_32/lib/Qt5Widgets.prl \
		C:/qt51/5.1.1/mingw48_32/lib/Qt5Sql.prl \
		C:/qt51/5.1.1/mingw48_32/lib/Qt5Gui.prl \
		C:/qt51/5.1.1/mingw48_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VocabBuilder.pro
../../qt51/5.1.1/mingw48_32/mkspecs/features/spec_pre.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/qdevice.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/features/device_config.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/common/shell-unix.conf:
../../qt51/5.1.1/mingw48_32/mkspecs/qconfig.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axbase.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_axserver.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_clucene.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_core.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_declarative.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_designer.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_designercomponents.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_gui.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_help.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_network.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_opengl.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_platformsupport.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qml.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qmldevtools.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_quick.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_quickparticles.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_script.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_sensors.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_serialport.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_sql.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_svg.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_testlib.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_uitools.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_v8.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_webkit.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_widgets.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_xml.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt51/5.1.1/mingw48_32/mkspecs/features/qt_functions.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/qt_config.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/win32-g++/qmake.conf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/spec_post.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/exclusive_builds.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/default_pre.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/default_pre.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/resolve_config.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/default_post.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/qml_debug.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/declarative_debug.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/rtti.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/warn_on.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/qt.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/resources.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/moc.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/opengl.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/uic.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/win32/windows.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/testcase_targets.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/exceptions.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/yacc.prf:
../../qt51/5.1.1/mingw48_32/mkspecs/features/lex.prf:
VocabBuilder.pro:
C:/qt51/5.1.1/mingw48_32/lib/Qt5Widgets.prl:
C:/qt51/5.1.1/mingw48_32/lib/Qt5Sql.prl:
C:/qt51/5.1.1/mingw48_32/lib/Qt5Gui.prl:
C:/qt51/5.1.1/mingw48_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile VocabBuilder.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
